### ISSUE TITLE
Item schema update breaks GetParticleAttributeSystemName

### ISSUE THREAD

**Issue by M4thx** [nosoop/SM-TFEconData#14]
This address cache becomes invalid when the item schema is updated, resulting in an infinite loop when the native TF2Econ_GetParticleAttributeSystemName is called.

https://github.com/nosoop/SM-TFEconData/blob/master/scripting/tf_econ_data/attached_particle_systems.sp#L213-#L217

**Comment by nosoop** [comment]
Ah, good catch!  That's one of the cases I overlooked.

This will be fixed shortly &mdash; it's probably fine enough just to never cache that information.  If the performance is really bad, I think it'd be safe to bring back caching if invalidation is forced based on the schema's internal reset counter.
