### ISSUE TITLE
(Suggestion/Question) Stand-in for TF2Items

### ISSUE THREAD

**Issue by SnowySnowtime** [nosoop/SM-TFEconData#15]
This one is a bit of a stretch or a doozy, but I'll give an ask anyways.
Is there a possibility to have a wrapper of EconData for TF2Items; or a replacement? Such as being able to use it to edit in-game weapon attributes like how Tf2Items can currently. My friend wants to be able to do something like this to keep a player's skins and other content, but have his re-balances work with them at the same time, even up to having a persistent opt-in feature.

Wasn't sure where to ask, I don't really look around anywhere else but github, so I apologize if this wouldn't go here. I don't mind if this isn't possible, I'm asking more-so out of curiosity.

**Comment by nosoop** [comment]
It's outside the scope of this project, but it's possible in theory.

TF2Items's attribute setters modifies runtime attributes, so it wouldn't be too far off from what something like [Rebalance Fortress 2](https://github.com/JugadorXEI/tf2rebalance_jug) is doing, just substituting TF2Items with DHooks and TF2Attributes (aside from some differences at a technical level).

If you're already aware of that project, I'd be somewhat interested in knowing why it doesn't work for your friend.

**Comment by SnowySnowtime** [comment]
My friend hasn't seen that. I'll have him take a look. Thanks for the answer. I'll let you know how it goes.

**Comment by nosoop** [comment]
Alrighty.  Going to close this since it's not within the project's scope, but you're welcome to reply here without reopening the issue.
