### ISSUE TITLE
Some localization tokens do not match tf_english.txt

### ISSUE THREAD

**Issue by jVu7Dv7siFzvXj** [nosoop/SM-TFEconData#16]
I am using [LanguagePhrasesParser](https://github.com/Natanel-Shitrit/LanguagePhrasesParser) to get `tf_english.txt` phrases into a translation file combined with this to make an item menu plugin. However, some localization tokens break when translating as it is case sensitive. For example `TF2Econ_GetLocalizedItemName` returns `TF_Unique_Achievement_Flaregun` but `tf_english.txt` has it as `TF_Unique_Achievement_FlareGun`. Is it because the name in memory is different than the name on file or something else? Thanks.

**Comment by nosoop** [comment]
The `item_name` value in `items_game.txt` is `#TF_Unique_Achievement_Flaregun`; the game is parsing the item schema and storing that string in memory as-is.

However, Valve's localization system performs a case-insensitive match for localization token lookups, so the behavior of the game and your plugin (or SourceMod's translation system) behaves differently in that way.

**Comment by nosoop** [comment]
It's tightly coupled to the client-only VGUI / localization system; not possible.

You'll want to normalize the case of both the string you get from `TF2Econ_GetLocalizedItemName()` and the localization tokens output by LanguagePhrasesParser (that is, edit the translation file).  Easiest would be to make them all consistently upper / lower case.
