### ISSUE TITLE
Full particle attribute lookup crashes on Windows

### ISSUE THREAD

**Issue by M4thx** [nosoop/SM-TFEconData#19]
Full particle lookup is crashing about half of the time for me on Windows using this code:

```SourcePawn
#include <sourcemod>
#include <tf_econ_data>

public void OnAllPluginsLoaded() {
    TF2Econ_GetParticleAttributeList();
}
```

https://crash.limetech.org/qbkmm4kmwxgk

Plugin call stacktrace is
```
EXCEPTION_ACCESS_VIOLATION_READ accessing 0x1b286fea

sourcemod.logic.dll!LoadFromAddress
tf_econ_data.smx::GetParticleSystemTreeElement
tf_econ_data.smx::IsParticleSystemRightChild 
tf_econ_data.smx::GetNextParticleSystem
tf_econ_data.smx::GetParticleAttributeList
tf_econ_data.smx::Native_GetParticleAttributeList
```

On Linux it works fine.

I did investigate a little and seems like the culprit is [IsParticleSystemRightChild](https://github.com/nosoop/SM-TFEconData/blob/933afb2ef6c7074a07b85520fad0f2b23774ea93/scripting/tf_econ_data/attached_particle_systems.sp#L206-L209) as it doesn't check if the parent is valid before interacting with it.

Adding an extra check (`parent != 0xFFFF`) fixed the problem for me.

**Comment by nosoop** [comment]
Thanks! I'm able to reproduce this issue; it will be addressed shortly in the next release.
