### ISSUE TITLE
TF2Econ_TranslateWeaponEntForClass fails to translate classname despite returning true

### ISSUE THREAD

**Issue by Mikusch** [nosoop/SM-TFEconData#21]
In certain cases `TF2Econ_TranslateWeaponEntForClass` fails to properly translate a weapon classname and clears the buffer, despite returning `true`. I've tried a couple different weapons but from the ones I've tested only `tf_weapon_parachute` causes this result.

If this is a TF2 issue, the library should probably check whether the returned buffer actually contains data and factor that into the return value for `TF2Econ_TranslateWeaponEntForClass`.

```sourcepawn
#include <tf_econ_data>

public void OnPluginStart()
{
	char weaponName[64];
	strcopy(weaponName, sizeof(weaponName), "tf_weapon_parachute");
	
	LogMessage("Weapon name before translation: %s", weaponName);
	
	if (TF2Econ_TranslateWeaponEntForClass(weaponName, sizeof(weaponName), TFClass_Engineer))
	{
		LogMessage("Successfully translated");
	}
	
	LogMessage("Weapon name after translation: %s", weaponName);
}
```
```
L 06/03/2023 - 18:36:47: [disabled\econtest.smx] Weapon name before translation: tf_weapon_parachute
L 06/03/2023 - 18:36:47: [disabled\econtest.smx] Successfully translated
L 06/03/2023 - 18:36:47: [disabled\econtest.smx] Weapon name after translation:
```

**Comment by nosoop** [comment]
Turns out I was getting bit by `TranslateWeaponEntForClass` returning a `nullptr`, and that causes `SDKCall` to return -1 (as opposed to 0, being an empty string).  I could've sworn I tested for this ages ago, but I guess not.

Deploying a fix shortly; thanks for the report!
