### ISSUE TITLE
Econ Taunts broken after newest update.

### ISSUE THREAD

**Issue by gdfsgdfg** [nosoop/SM-TFEconData#22]
https://github.com/x07x08/TF2-Econ-Taunts

I'm guessing it as a gamedata related issue with econ data.

Using version 0.19.1.1

**Comment by nosoop** [comment]
Hi &mdash; any error messages to reduce the guesswork?  That plugin also has gamedata that may have also broken (definitely on Windows).

**Comment by gdfsgdfg** [comment]
Oh yeah I didn't notice the other one tf2.tauntem.txt could be at fault I've tried 2 other taunt plugins that use it and don't seem to work either.

I am on windows srcds.
