### ISSUE TITLE
newest TF2 update, econ data still broken

### ISSUE THREAD

**Issue by artvin01** [nosoop/SM-TFEconData#23]
tf_econ_data.smx::.31244.GetEconAttributeDefinition 
tf_econ_data.smx::.15816.Native_GetAttributeDefinitionString

calling these still immedietly crashes the server.
I presume the signatures are wrong or something else changed.

**Comment by artvin01** [comment]
Short followup
i can confirm that 
TF2Econ_GetAttributeDefinitionString
crashes the server, i removed this code that calls this and it doesnt crash anymore, ill look into it incase there is a missing signature.

**Comment by artvin01** [comment]
im unsure how to fix this myself, seems like no signature is attached, ill wait.

**Comment by nosoop** [comment]
Closed by #24.

**Comment by nosoop** [comment]
Reopened because apparently the PR was also broken.

**Comment by nosoop** [comment]
Reclosing because the PR has been reverified.
