### ISSUE TITLE
Possible to update releases?

### ISSUE THREAD

**Issue by artvin01** [nosoop/SM-TFEconData#27]
It seems like it is outdated.
![image](https://github.com/user-attachments/assets/83db56b8-bd55-412c-9427-d5cf41a3fc21)
![image](https://github.com/user-attachments/assets/fd807e78-001a-4897-82a5-6a90840433e7)

Confuses people installing my gamemode, as they are getting old gamedata on accident, thanks ahead of time!

**Comment by nosoop** [comment]
Done; forgot to mark it as latest I guess.
