### ISSUE TITLE
Using TF2Econ_GetItemDefinitionString or TF2Econ_GetAttributeDefinitionString crashes the server if the key exists.

### ISSUE THREAD

**Issue by spundarce** [nosoop/SM-TFEconData#7]
I was attempting to make 2 functions: the first one was to find the weapon's model from it's itemdef, while the second one was to determine if an attribute was percentage based it's "description_format" key. Using either native to find a key on Windows returns a "Engine error: NUM_FOR_EDICT: bad pointer" or a SDKCall crash. Searching for a non-existent key does not crash the server.

**Comment by nosoop** [comment]
Thank you for the report!
It looks like the existing signature for `KeyValues::GetString()` isn't unique anymore, and I suspect that SourceMod is resolving the pattern to `CTFPlayer::Event_Killed()` instead; that would line up with the crash on keys that do exist.  Will push out a fix for that shortly.

**Comment by nosoop** [comment]
I've pushed out a fix; let me know if it works so the issue can be closed up.
I'll probably test it myself later as well, don't have the time at this instant.

**Comment by nosoop** [comment]
Updated byte signature is correct.
